CREATE TABLE STATISTICS_GAME
(
DATE_STATISTICS DATE NOT NULL,
NUMER_PLAYER_STATISTIC NUMBER(*,0) NOT NULL,

CONSTRAINT STATISTICS_GAME_PK PRIMARY KEY (DATE_STATISTICS)
)




CREATE TABLE PLAYER 
(
ID_PLAYER NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
EMAIL_PLAYER VARCHAR2(50) NULL,
BOT NUMBER(1,0) DEFAULT 0 NOT NULL,
NAME_PLAYER VARCHAR2(50) NOT NULL,
PASSWORD_PLAYER CHAR(64) NOT NULL,
WINS_PLAYER NUMBER(*,0) DEFAULT 0 NOT NULL,
LOSING_PLAYER NUMBER(*,0) DEFAULT 0 NOT NULL,
TIE_PLAYER NUMBER(*,0) DEFAULT 0 NOT NULL,                                          --??
BALANCE NUMBER(*,0) DEFAULT 0 NOT NULL,

CONSTRAINT PLAYER_PK PRIMARY KEY (ID_PLAYER)
)


CREATE TABLE GAMING_TABLE
(
ID_TABLE NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
NAME_TABLE VARCHAR2(50) NOT NULL,
COST_TABLE NUMBER(*,0) NOT NULL,
PATCH_TABLE VARCHAR2(50) NOT NULL,

CONSTRAINT GAMING_TABLE_PK PRIMARY KEY (ID_TABLE)
)


CREATE TABLE BOUGHT_GAMING_TABLE
(
PLAYER_BOUGHT_TABLE NUMBER NOT NULL,
TABLE_BOUGHT_TABLE NUMBER NOT NULL,

CONSTRAINT BOUGHT_GAMING_TABLE_PK PRIMARY KEY (PLAYER_BOUGHT_TABLE, TABLE_BOUGHT_TABLE),
CONSTRAINT BOUGHT_TABLE_PLAYER_FK FOREIGN KEY (PLAYER_BOUGHT_TABLE) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT BOUGHT_TABLE_GAMING_TABLE_FK FOREIGN KEY (TABLE_BOUGHT_TABLE) REFERENCES GAMING_TABLE (ID_TABLE)
)


CREATE TABLE BACK
(
ID_BACK NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
NAME_BACK VARCHAR2(50) NOT NULL,
COST_BACK NUMBER(*,0) NOT NULL,
PATCH_BACK VARCHAR2(50) NOT NULL,

CONSTRAINT BACK_PK PRIMARY KEY (ID_BACK)
)


CREATE TABLE BOUGHT_BACK
(
PLAYER_BOUGHT_BACK NUMBER NOT NULL,
BACK_BOUGHT_BACK NUMBER NOT NULL,

CONSTRAINT BOUGHT_BACK_PK PRIMARY KEY (PLAYER_BOUGHT_BACK, BACK_BOUGHT_BACK),
CONSTRAINT BOUGHT_BACK_PLAYER_FK FOREIGN KEY (PLAYER_BOUGHT_BACK) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT BOUGHT_BACK_BACK_FK FOREIGN KEY (BACK_BOUGHT_BACK) REFERENCES BACK (ID_BACK)
)


CREATE TABLE FACE
(
ID_FACE NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
NAME_FACE VARCHAR2(50) NOT NULL,
COST_FACE NUMERIC(*,0) NOT NULL,
PATCH_FACE VARCHAR2(50) NOT NULL,

CONSTRAINT FACE_PK PRIMARY KEY (ID_FACE)
)


CREATE TABLE BOUGHT_FACE
(
PLAYER_BOUGHT_FACE NUMBER NOT NULL,
FACE_BOUGHT_FACE NUMBER NOT NULL,

CONSTRAINT BOUGHT_FACE_PK PRIMARY KEY (PLAYER_BOUGHT_FACE, FACE_BOUGHT_FACE),
CONSTRAINT BOUGHT_FACE_PLAYER_FK FOREIGN KEY (PLAYER_BOUGHT_FACE) REFERENCES PLAYER(ID_PLAYER),
CONSTRAINT BOUGHT_FACE_FACE_FK FOREIGN KEY (FACE_BOUGHT_FACE) REFERENCES FACE(ID_FACE)
)


CREATE TABLE COMMENT_PLAYER
(
ID_COMMENT NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
PLAYER_COMMENT NUMBER NOT NULL,
TEXT_COMMENT VARCHAR2(1000) NOT NULL,

CONSTRAINT COMMENT_PLAYER_PK PRIMARY KEY (ID_COMMENT),
CONSTRAINT COMMENT_PLAYER_PLAYER_FK FOREIGN KEY (PLAYER_COMMENT) REFERENCES PLAYER (ID_PLAYER)
)


CREATE TABLE LAST_RESULTS_PLAYER
(
ID_RESULT NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
PLAYER_RESULT NUMBER NOT NULL,
OPPONENT_RESULT NUMBER NOT NULL,
RESULT_RESULT NUMBER(1,0) NOT NULL,

CONSTRAINT LAST_RESULTS_PLAYER_PK PRIMARY KEY (ID_RESULT),
CONSTRAINT RESULT_PLAYER_FK FOREIGN KEY (PLAYER_RESULT) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT RESULT_OPPONENT_FK FOREIGN KEY (OPPONENT_RESULT) REFERENCES PLAYER (ID_PLAYER)
)


CREATE TABLE FRIEND
(
ID_FRIEND NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
PLAYER1_FRIEND NUMBER NOT NULL,
PLAYER2_FRIEND NUMBER NOT NULL,
WINS_PLAYER1_FRIEND NUMBER DEFAULT 0 NOT NULL,
WINS_PLAYER2_FREIND NUMBER DEFAULT 0 NOT NULL,
TIE_FRINED NUMBER DEFAULT 0 NOT NULL,

CONSTRAINT FRIEND_PK PRIMARY KEY (ID_FRIEND),
CONSTRAINT PLAYER1_FRIEND_FK FOREIGN KEY (PLAYER1_FRIEND) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT PLAYER2_FRIEND_FK FOREIGN KEY (PLAYER2_FRIEND) REFERENCES PLAYER (ID_PLAYER)
)


CREATE TABLE RESULTS_FRIEND
(
ID_RESULTS_FRIEND NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
FRIEND_RESULTS_FRIEND NUMBER NOT NULL,
RESULT_RESULTS_FRIEND NUMBER(1,0) NOT NULL,

CONSTRAINT RESULTS_FRIEND_PK PRIMARY KEY (ID_RESULTS_FRIEND),
CONSTRAINT FRIEND_RESULTS_FRIEND_FK FOREIGN KEY (FRIEND_RESULTS_FRIEND) REFERENCES FRIEND (ID_FRIEND)
)


CREATE TABLE SAVED_GAME_2_PLAYER
(
ID_SAVED_2 NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
PLAYER_1_SAVED_2 NUMBER NOT NULL,
PLAYER_2_SAVED_2 NUMBER NOT NULL,
CARDS_PLAYER_1_SAVED_2 VARCHAR2(120) NOT NULL,
CARDS_PLAYER_2_SAVED_2 VARCHAR2(120) NOT NULL,
CARDS_RESIDUAL_SAVED_2 VARCHAR2(120) NOT NULL,
TRUMP_CARD_SAVED_2 VARCHAR2(3) NOT NULL,

CONSTRAINT SAVED_GAME_2_PLAYER_PK PRIMARY KEY (ID_SAVED_2),
CONSTRAINT PLAYER_1_SAVED_2_FK FOREIGN KEY (PLAYER_1_SAVED_2) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT PLAYER_2_SAVED_2_FK FOREIGN KEY (PLAYER_2_SAVED_2) REFERENCES PLAYER (ID_PLAYER)
)


CREATE TABLE SAVED_GAME_3_PLAYER
(
ID_SAVED_3 NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
PLAYER_1_SAVED_3 NUMBER NOT NULL,
PLAYER_2_SAVED_3 NUMBER NOT NULL,
PLAYER_3_SAVED_3 NUMBER NOT NULL,
CARDS_PLAYER_1_SAVED_3 VARCHAR2(120) NOT NULL,
CARDS_PLAYER_2_SAVED_3 VARCHAR2(120) NOT NULL,
CARDS_PLAYER_3_SAVED_3 VARCHAR2(120) NOT NULL,
CARDS_RESIDUAL_SAVED_3 VARCHAR2(120) NOT NULL,
TRUMP_CARD_SAVED_3 VARCHAR2(3) NOT NULL,

CONSTRAINT SAVED_GAME_3_PLAYER_PK PRIMARY KEY (ID_SAVED_3),
CONSTRAINT PLAYER_1_SAVED_3_FK FOREIGN KEY (PLAYER_1_SAVED_3) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT PLAYER_2_SAVED_3_FK FOREIGN KEY (PLAYER_2_SAVED_3) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT PLAYER_3_SAVED_3_FK FOREIGN KEY (PLAYER_3_SAVED_3) REFERENCES PLAYER (ID_PLAYER)
)


CREATE TABLE SAVED_GAME_4_PLAYER
(
ID_SAVED_4 NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
PLAYER_1_SAVED_4 NUMBER NOT NULL,
PLAYER_2_SAVED_4 NUMBER NOT NULL,
PLAYER_3_SAVED_4 NUMBER NOT NULL,
PLAYER_4_SAVED_4 NUMBER NOT NULL,
CARDS_PLAYER_1_SAVED_4 VARCHAR2(120) NOT NULL,
CARDS_PLAYER_2_SAVED_4 VARCHAR2(120) NOT NULL,
CARDS_PLAYER_3_SAVED_4 VARCHAR2(120) NOT NULL,
CARDS_PLAYER_4_SAVED_4 VARCHAR2(120) NOT NULL,
CARDS_RESIDUAL_SAVED_4 VARCHAR2(120) NOT NULL,
TRUMP_CARD_SAVED_4 VARCHAR2(3) NOT NULL,

CONSTRAINT SAVED_GAME_4_PLAYER_PK PRIMARY KEY (ID_SAVED_4),
CONSTRAINT PLAYER_1_SAVED_4_FK FOREIGN KEY (PLAYER_1_SAVED_4) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT PLAYER_2_SAVED_4_FK FOREIGN KEY (PLAYER_2_SAVED_4) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT PLAYER_3_SAVED_4_FK FOREIGN KEY (PLAYER_3_SAVED_4) REFERENCES PLAYER (ID_PLAYER),
CONSTRAINT PLAYER_4_SAVED_4_FK FOREIGN KEY (PLAYER_4_SAVED_4) REFERENCES PLAYER (ID_PLAYER)
)